# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: locket.proto for package 'cloud_foundry.locket'

require 'grpc'
require 'locket/locket_pb'

module CloudFoundry
  module Locket
    module Locket
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'cloud_foundry.locket.Locket'

        rpc :Lock, LockRequest, LockResponse
        rpc :Fetch, FetchRequest, FetchResponse
        rpc :Release, ReleaseRequest, ReleaseResponse
        rpc :FetchAll, FetchAllRequest, FetchAllResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
