# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locket.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cloud_foundry.locket.Resource" do
    optional :key, :string, 1
    optional :owner, :string, 2
    optional :value, :string, 3
    optional :type, :string, 4
    optional :type_code, :enum, 5, "cloud_foundry.locket.TypeCode"
  end
  add_message "cloud_foundry.locket.LockRequest" do
    optional :resource, :message, 1, "cloud_foundry.locket.Resource"
    optional :ttl_in_seconds, :int64, 2
  end
  add_message "cloud_foundry.locket.LockResponse" do
  end
  add_message "cloud_foundry.locket.ReleaseRequest" do
    optional :resource, :message, 1, "cloud_foundry.locket.Resource"
  end
  add_message "cloud_foundry.locket.ReleaseResponse" do
  end
  add_message "cloud_foundry.locket.FetchRequest" do
    optional :key, :string, 1
  end
  add_message "cloud_foundry.locket.FetchResponse" do
    optional :resource, :message, 1, "cloud_foundry.locket.Resource"
  end
  add_message "cloud_foundry.locket.FetchAllRequest" do
    optional :type, :string, 1
    optional :type_code, :enum, 2, "cloud_foundry.locket.TypeCode"
  end
  add_message "cloud_foundry.locket.FetchAllResponse" do
    repeated :resources, :message, 1, "cloud_foundry.locket.Resource"
  end
  add_enum "cloud_foundry.locket.TypeCode" do
    value :UNKNOWN, 0
    value :LOCK, 1
    value :PRESENCE, 2
  end
end

module CloudFoundry
  module Locket
    Resource = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.locket.Resource").msgclass
    LockRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.locket.LockRequest").msgclass
    LockResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.locket.LockResponse").msgclass
    ReleaseRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.locket.ReleaseRequest").msgclass
    ReleaseResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.locket.ReleaseResponse").msgclass
    FetchRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.locket.FetchRequest").msgclass
    FetchResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.locket.FetchResponse").msgclass
    FetchAllRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.locket.FetchAllRequest").msgclass
    FetchAllResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.locket.FetchAllResponse").msgclass
    TypeCode = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.locket.TypeCode").enummodule
  end
end
